"""add chat threads

Revision ID: 1480e95b0f1c
Revises: 55641e2e17b1
Create Date: 2026-09-24 14:00:39.242827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1480e95b0f1c'
down_revision: Union[str, Sequence[str], None] = '55641e2e17b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['jds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_jd_id'), 'chat_threads', ['jd_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_profile_id'), 'chat_threads', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_threads_profile_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_jd_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
