"""initial_schema

Revision ID: 55641e2e17b1
Revises: 
Create Date: 2026-09-18 11:30:38.816520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55641e2e17b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('structured', sa.JSON(), nullable=True),
    sa.Column('role_type', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jds_role_type'), 'jds', ['role_type'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jd_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['jd_id'], ['jds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_requirements_jd_id'), 'jd_requirements', ['jd_id'], unique=False)
    op.create_table('profile_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_facts_profile_id'), 'profile_facts', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_facts_section'), 'profile_facts', ['section'], unique=False)
    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('jd_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('resume_pdf_path', sa.String(length=512), nullable=True),
    sa.Column('cover_pdf_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['jds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_logs_jd_id'), 'run_logs', ['jd_id'], unique=False)
    op.create_index(op.f('ix_run_logs_profile_id'), 'run_logs', ['profile_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_log_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('cited_fact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cited_fact_id'], ['profile_facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_log_id'], ['run_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_cited_fact_id'), 'claims', ['cited_fact_id'], unique=False)
    op.create_index(op.f('ix_claims_run_log_id'), 'claims', ['run_log_id'], unique=False)
    op.create_index(op.f('ix_claims_state'), 'claims', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_state'), table_name='claims')
    op.drop_index(op.f('ix_claims_run_log_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_cited_fact_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_run_logs_profile_id'), table_name='run_logs')
    op.drop_index(op.f('ix_run_logs_jd_id'), table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_index(op.f('ix_profile_facts_section'), table_name='profile_facts')
    op.drop_index(op.f('ix_profile_facts_profile_id'), table_name='profile_facts')
    op.drop_table('profile_facts')
    op.drop_index(op.f('ix_jd_requirements_jd_id'), table_name='jd_requirements')
    op.drop_table('jd_requirements')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_jds_role_type'), table_name='jds')
    op.drop_table('jds')
    # ### end Alembic commands ###
